export enum Operacao {
  LIBERACAO_SC = 'liberarsaldo',
  CANCELAR_LIBERACAO_SC = 'cancelarliberacao',
  PREENCHER_NDO_VALOR = 'preencherndovalor',
  PREENCHER_NDO_ITEM_SOLIC = 'preencherndoitemsolic',
  EXIBIR_HIST_LIBERACAO = 'exibirhistliberacao',
  HISTORICO_CANCELAMENTO = 'historicocancelamento',
  //financeiro
  COTACAO_PROPOSTA = 'cotacaoproposta',
  ANALISAR_PROPOSTA = 'analisarproposta',
  PESQUISAR = 'pesquisar',
  INCLUIR = 'incluir',
  ALTERAR = 'alterar',
  ENCERRAMENTO = 'encerramento',
  DETALHAR = 'detalhar',
  EXCLUIR = 'excluir',
  COPIAR = 'copiar',
  CANCELAR = 'cancelar',
  ATENDER = 'atender',
  ESTORNAR = 'estornar',
  ASSOCIAR_CONTA = 'associarconta',
  ASSOCIAR_GRUPO_CENTRO_CUSTO = 'associargrupocentrocusto',
  IMPRIMIR = 'imprimir',
  REPORT_DESIGNER = 'reportDesigner',
  RELATORIO = 'relatorio',
  IMPORTAR = 'importar',
  INCLUIR_APLICACAO = 'incluirAplicacao',
  INCLUIR_ITEM = 'incluiritem',
  ALTERAR_ITEM = 'alteraritem',
  DETALHAR_ITEM = 'detalharitem',
  INCLUIR_FABRICANTE = 'incluirfabricante',
  ALTERAR_FABRICANTE = 'alterarfabricante',
  DETALHAR_FABRICANTE = 'detalharfabricante',
  INCLUIR_IMPOSTO = 'incluirimposto',
  ALTERAR_IMPOSTO = 'alterarimposto',
  DETALHAR_IMPOSTO = 'detalharimposto',
  LIBERAR_SALDO = 'liberarsaldo',
  CANCELAR_SALDO = 'cancelarsaldo',
  GERAR_BORDERO = 'gerarbordero',

  DETALHAR_TITULO_BORDERO = 'detalhartitulobordero',
  DETALHAR_BORDERO_ORIGEM ='detalharBorderoOrigem',
  ALTERAR_BORDERO_ORIGEM ='detalharBorderoOrigem',
  CADASTAR_NOVA_CONTA_CONTABIL = 'cadastrarnovacontacontabil',
  CONTA_DE_ADIANTAMENTO_INCLUIR = 'contaadiantamentoincluir',
  HISTORICO = 'historico',
  CADASTRAR_CONTA_ADIANTAMENTO = 'cadastrarcontaadiantamento',

  //financeiro
  ALTERAR_PARTICIPACAO_SOCIETARIA = 'alterarparticipacaosocietaria',
  INCLUIR_PARTICIPACAO_SOCIETARIA = 'incluirparticipacaosocietaria',
  INCLUIR_TITULO_NDO = 'incluirtitulondo',
  ALTERAR_TITULO_NDO = 'alterartitulondo',
  DETALHAR_TITULO_NDO = 'detalhartitulondo',
  DETALHAR_BAIXA = 'detalharbaixa',
  ALTERAR_BAIXA = 'alterarBaixa',
  INCLUIR_EXTRATO_BANCARIO = 'incluirExtratoBancario',
  DETALHAR_EXTRATO_BANCARIO = 'detalharExtratoBancario',
  DETALHAR_TITULO_RECEBER_EXTRATO = 'detalharTituloReceberExtrato',
  DETALHAR_TITULO_RECEBER_ENCONTRO_CONTAS = 'detalharTituloReceberEncontroContas',
  DETALHAR_TITULO_PAGAR_ENCONTRO_CONTAS = 'detalharTituloPagarEncontroContas',
  DETALHAR_ORIGEM_TITULO_PAGAR_ENCONTRO_CONTAS = 'detalharOrigemTituloPagarEncontroContas',
  DETALHAR_RETORNO_PAGAMENTO = 'detalharRetornoOagamento',
  PESQUISAR_RETORNO_PAGAMENTO = 'pesquisarRetornoPagamento',
  DETALHAR_TITULO_PAGAR_EXTRATO = 'detalharTituloPagarExtrato',
  ALTERAR_BAIXA_EXTRATO = 'alterarExtratoBancario',
  ALTERAR_TITULO_PAGAR_EXTRATO = 'alterarTituloPagarExtrato',
  DETALHAR_TITULO_RECEBER = 'detalharTituloReceber',
  DETALHAR_TITULO_PAGAR = 'detalharTituloPagar',
  ALTERAR_TITULO_PAGAR = 'alterarPagamento',
  //INCLUIR_EMPRESA = 'incluirempresa',
  //ALTERAR_EMPRESA = 'alterarempresa' ,
  INCLUIR_CONTA_CONTABIL = 'incluircontacontabil',
  ALTERAR_CONTA_CONTABIL = 'alterarcontacontabil',
  ALTERAR_CLIENTE_FILIAL = 'alterarclientefilial',
  INCLUIR_CLIENTE_FILIAL = 'incluirclientefilial',
  DETALHAMENTO_FINANCEIRO = 'detalhamentofinanceiro',
  DETALHAMENTO_CLIENTE = 'detalhamentocliente',
  DETALHAMENTO_TITULO_RECEBER_HISTORICO_SUBSTITUICOES = 'detalhamentohistoricosubstituicoestituloreceber',
  INCLUIR_BORDERO_DESPESA = "incluirborderodespesa",
  ALTERAR_BORDERO_DESPESA = "alterarborderodespesa",
  DETALHAR_BORDERO_DESPESA = "detalharborderodespesa",
  INCLUIR_BORDERO_ADIANTAMENTO = "incluirborderoadiantamento",
  ALTERAR_BORDERO_ADIANTAMENTO = "alterarborderoadiantamento",
  DETALHAR_BORDERO_ADIANTAMENTO = "detalharborderoadiantamento",
  INCLUIR_BORDERO_DEVOLVER = "incluirborderodevolver",
  ALTERAR_BORDERO_DEVOLVER = "alterarborderodevolver",
  DETALHAR_BORDERO_DEVOLVER = "detalharborderodevolver",
  DETALHAR_LANCAMENTO_BORDERO_DEVOLVER = "detalharlancamentoborderodevolver",
  INCLUIR_CONTA_ADIANTAMENTO = "incluircontaadiantamento",
  DETALHLAR_CONTA_ADIANTAMENTO = "detalharcontaadiantamento",
  ALTERAR_CONTA_ADIANTAMENTO = "alterarcontaadiantamento",
  RECIBO_PAGAMENTO = 'recibopagamento',
  MOVIMENTACAO_INTERNA = 'movimentacaointerna',
  INCLUIR_CONTA_CORRENTE = 'incluircontacorrente',
  DETALHAR_CONCILIACAO = 'detalharconciliacao',
  //AUTORIZAÇÃO DE FORNECIMENTO
  INCLUIR_OBSERVACAO = 'incluirobservacao',
  ALTERAR_OBSERVACAO = 'alterarobservacao',
  DETALHAR_OBSERVACAO = 'detalharobservacao',
  DETALHAR_AF_TITULO = 'aftitulodetalhar',
  BAIXA_AF = 'baixaaf',
  AJUSTAR_VENCIMENTO = 'ajustarvencimento',
  ASSOCIAR_DEPARTAMENTO_FILIAL = 'associardepartamentofilial',
  DETALHAR_SOLICITACAO = 'detalharsolicitacao',
  ADIANTAMENTO_CONCEDIDO = 'adiantamentoconcedido',
  ADIANTAMENTO_RECEBIDO = 'adiantamentorecebido',
  RECEBIMENTO_ADIANTAMENTO = "recebimentoadiantamento",
  DEVOLUCAO = "devolucao",
  ALTERAR_DEVOLUCAO = 'alterardevolucao',
  DETALHAR_DEVOLUCAO = 'detalhardevolucao',
  PRESTACAO_CONTAS = "prestacaocontas",
  LANCAMENTO_TRANSFERIR = "lancamentotransferir",
  LANCAMENTO_RECIBO = "lancamentorecibo",
  //COTAÇÂO DE COMPRA
  INCLUIR_FORNECEDOR = 'incluirfornecedor',
  ALTERAR_FORNECEDOR = 'alterarfornecedor',
  DETALHAR_FORNECEDOR = 'detalharfornecedor',
  CONDICAO_PAGAMENTO = 'condicaopagamento',
  CONDICAO_PAGAMENTO_ALTERAR = 'condicaopagamentoalterar',
  REABRIR = 'reabrir',
  ANALISAR = 'analisar',
  PENDENCIAS = 'pendencias',
  CANCELAMENTO_NF ='cancelamentonotafiscal',
  HISTORICO_NEGOCIACAO = 'historiconegociacao',
  DETALHAR_COTACAO = 'detalharcotacao',
  //SOLICITACAO DE COMPRA
  DOCUMENTO_NOTA_FISCAL_SAIDA = 'documentonotafiscalsaida',

  INCLUIR_DOCUMENTO = 'incluirdocumento',
  ALTERAR_DOCUMENTO = 'alterardocumento',
  DETALHAR_DOCUMENTO = 'detalhardocumento',
  //PEDIDO
  DETALHAMENTO_GERENCIAL = 'detalhamentogerencial',
  INCLUIR_COTACAO_SOLIC = 'incluircotacaosolic',
  INCLUIR_COTACAO_ITENS_SOLIC = 'incluircotacaoitenssolic',
  INCLUIR_AF_SOLIC = 'incluirAFsolic',
  INCLUIR_AF_ITENS_SOLIC = 'incluirafitenssolic',
  INCLUIR_AF_ITENS_ESCOLHIDOS = 'incluirAFitensEscolhidos',
  DETALHAR_CLIENTE_FILHA = 'detalharClienteFilha',
  ALTERAR_CLIENTE_FILHA = 'alterarClienteFilha',
  INCLUIR_CLIENTE_FILHA = 'incluirClienteFilha',
  OCORRENCIA_PEDIDO = 'ocorrenciapedido',
  LIBERAR_BLOQUEIO = 'liberarbloqueio',
  PROGRAMACAO_ADIANTAMENTO = 'programacaoadiantamento',
  ASSOCICAO_PEDIDO_TRANSPORTADORA = 'assocaicaotransportadora',
  AUTORIZAR_PEDIDO_VENDA = 'autorizarpedido',
  AUTORIZAR_BLOQUEIO = 'autorizarbloqueio',
  CANCELAR_PEDIDO_ABERTO = 'cancelarpedidoaberto',
  CANCELAR_PEDIDO = 'cancelarpedido',
  DETALHAR_LANCAMENTO = 'detalharLancamento',
  SUBSTITUICAO_TITULOS = 'substituicaoTitulos',
  ATUALIZARTITULOS = 'atualizarTitulos',
  RECEBER_TITULOS = 'receberTitulos',
  GLOSAR_TITULOS = 'glosarTitulos',
  DEPOSITO_TITULOS = 'depositoTitulo',
  RENEGOCIAR_TITULO = 'renegociarTitulo',
  RASTREAR_RENEGOCIACAO = 'rastrearRenegociacao',
  DETALHAR_RENEGOCIACAO = 'detalharRenegociacao',
  APROVAR_RENEGOCIACAO_TITULOS = 'aprovarRenegociacaoTitulos',
  ENCERRAR_RENEGOCIACAO_TITULOS = 'encerrarRenegociacao',
  QUEBRAR_ACORDO = 'quebrarAcordo',
  PESQUISAR_SUBSTITUICAO = 'pesquisarSubstituicao',
  DETALHAR_SUBSTITUIR = 'detalharSubstituir',
  SUBSTITUIR_IMPOSTO = 'substituirImposto',
  PAGAR_TITULO = "pagarTitulo",

  //REQUISICAO
  INCLUIR_SOLICITACAO_ITENS_REQ = 'incluirsolicitacaoitensreq',

  //ESTOQUE
  REQUISICAO_AGREGAR = 'requisicaoAgregar',
  REQUISICAO_HISTORICO = 'botaoRequisicaoHistorico',
  FATOR_CONVERSAO = 'fatorConversao',
  ESTOQUE_FILIAIS = 'consultaestoquefiliais',
  ESTOQUE_EMPRESAS = 'consultaestoqueempresas',
  CONSULTAR_MOVIMENTACAO = 'consultarmovimentacao',
  CRITICAS_RECALCULO = 'criticasrecalculo',

  //COMPRAS
  CONFIRMAR_ACEITE = 'confirmarAceite',
  EXIBIR_NF = 'exibirnf',
  ORCAMENTO_EMPRESARIAL = 'orcemp',
  INCLUIR_RECEBER_NF_AF= 'receberNF_AF',
  DETALHAR_REQUISICAO = 'detalharRequisicao',
  INCLUIR_RECEBER_NF_DEVOLUCAO_NFS = 'receberNF_Devolucao_NFS',
  DEVOLUCAO_SAIDA = 'devolucao_saida',
  INCLUIR_RECEBER_NF_ITENS_AF = 'receberNF_Itens_AF',
  DETALHAR_AF = 'detalharafitenspedidocompra',
  DETALHAR_NF = 'detalharNF',
  DETALHAR_NF_PROCESSO = 'detalharNF_Processo',
  INCLUIR_RECEBER_NF_COMPLEMENTAR= 'receberNF_Complementar',
  INCLUIR_CONHECIMENTO_FRETE= 'incluir_conhecimento_frete',
  RECEBER_CONHECIMENTO_FRETE= 'receber_conhecimento_frete',
  AJUSTAR_NF = 'ajustarNF',
  //CONTABILIDADE
  ASSOCIACAO = "associacao",
  VERIFICAR_CONSISTENCIA = 'verificarConsistencia',
  CONSULTA_DIVERGENCIA = 'consultaDivergencia',
  GERAR_LANCAMENTO_CONTABIL = 'gerarLancamentoContabil',
  DETALHAR_NFE_COMPLEMENTAR = 'detalhar_nfe_complementar',
  ALTERAR_NFE_COMPLEMENTAR = 'alterar_nfe_complementar',
  //SOLICITAÇÃO TRANSFERÊNCIA
  DETALHAR_TRANSFERENCIA = "DetalharTransferencia",
  DETALHAR_SOLICITACAO_TRANSFERENCIA = "detalharSolicitacaoTransferencia",

  //RP
  DETALHAR_TITULO_RP = "detalharTituloRP",
  DETALHAR_RECIBO_PAGAMENTO = 'detalharReciboPagamento',

  //Retorno
  RETORNO = "RetornoCobranca",

  //tranferencia de numerario

  DETALHAR_TRASNF_NUMERARIO = "detalharTransfNum",
  INCLUIR_TRASNF_SALDO = "incluirTransfSaldo",

  // Encontro de Contas
  CANCELAR_PROCESSO_ENCONTRO_CONTAS = 'cancelarProcessoEncontroContas',
  ENCERRAR = 'encerrar',
  CANCELAR_ENCERRAMENTO = 'cancelarEncerramento',

  //Conhecmento de frete
  DETALHAR_CF_TITULO = 'cfretetitulodetalhar',
  AJUSTAR = 'ajustar',

  ALTERAR_ADIANTAMENTO_CONCEDIDO = 'alterar-adiantamentoconcedido',
  DETALHAR_ADIANTAMENTO_CONCEDIDO = 'detalhar-adiantamentoconcedido',
  ALTERAR_ADIANTAMENTO_RECEBIDO = 'alterar-adiantamentorecebido',
  DETALHAR_ADIANTAMENTO_RECEBIDO = 'detalhar-adiantamentorecebido',

  // Solicitação de adiantamento
  INCLUIR_SOLIC_ADIANT_ORIGEM_AF = 'incluirSolicAdiantOrigemAF',
  LISTAR_SOLIC_ADIANT_ORIGEM_AF = 'listarSolicAdiantOrigemAF',
  ALTERAR_SOLIC_ADIANT_ORIGEM_AF = 'alterarSolicAdiantOrigemAF',
  DETALHAR_MOVIMENTACAO = 'detalharMovimentacao',

  // Solicitação de Reembolso
  DETALHAR_SOLICITACAO_REEMBOLSO = 'detalharSolicReembolso',

  //Cheque
  INCLUIR_CHEQUE_FORNECEDOR = 'incluirchequefornecedor',
  DETALHAR_CHEQUE_FORNECEDOR = 'detalharchequefornecedor',
  DETALHAR_CHEQUE_ADIANTAMENTO = 'detalharChequeAdiantamento',
  ALTERAR_CHEQUE_FORNECEDOR = 'alterarchequefornecedor',
  DETALHAR_CHEQUE_DESPESA = 'detalharChequeDespesa',

   // Solicitação de Reembolso
   DETALHAR_MOVIMENTACAO_SOLIC_REEMBOLSO = 'detalharMovimentacaoSolReembolso',

   INCLUIR_CONFIGURACAO_CONTABIL = 'incluirConfiguracaoContabil',
   ALTERAR_CONFIGURACAO_CONTABIL = 'alterarConfiguracaoContabil',
   DETALHAR_CONFIGURACAO_CONTABIL = 'detalharConfiguracaoContabil',

   //Cadastro de Pessoa
   INCLUIR_CLIENTE = 'incluirCliente',

   //Cadastro de Garantia de Bens
   CADASTRO_GARANTIA_BENS = 'cadastroGarantiaBens'
}
